version: '3.1'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    restart: always
    volumes:
      - ./web:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/edk.ini
    ports:
      - 8736:80
    links:
      - mysql
      - redis
    depends_on:
      - mysql

  cron:
    build:
      context: .
      dockerfile: Dockerfile-cron
    restart: always
    volumes:
      - ./crontab:/etc/cron.d/evekb
    links:
      - web
    depends_on:
      - web
    command: sh -c "touch /tmp/cronlogs && crond -s /etc/cron.d -b -L /tmp/cronlogs && tail -f /tmp/cronlogs"

  mysql:
    image: mysql:5.5
    restart: always
    environment:
      MYSQL_DATABASE: evekb
      MYSQL_ROOT_PASSWORD: evekb
      MYSQL_USER: evekb
      MYSQL_PASSWORD: evekb
    volumes:
      - ./mysql:/var/lib/mysql

  redis:
    image: redis:3.2-alpine
    restart: always
    volumes:
      - ./redis:/data
